# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: deliveroo.engineering
email: hello@deliveroo.engineering
description: > # this means to ignore newlines until "baseurl:"
  Deliveroo engineering blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://deliveroo.engineering" # the base hostname & protocol for your site
logo: /images/logo_engineering.svg
twitter:
  username: deliverooeng

repository: "deliveroo/deliveroo.engineering"

external_links:
  careers: "https://careers.deliveroo.co.uk/?team=engineering-team"

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
  toc_levels: 1..4

# Plugins
plugins:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed
   - jekyll-paginate
   - jekyll-seo-tag

paginate: 9
paginate_path: "/articles/page:num/"

collections:
  authors:
    output:       true
    permalink:    /authors/:path/

defaults:
  - scope:
      path:       ""
      type:       articles
    values:
      layout:     articles
  - scope:
      path: ""
    values:
      image:
        path: /images/og-deliveroo-engineering.png
        height: 630
        width: 1208
        type: image/svg
exclude:
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - token
  - bin
